language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO=2.0
  - DJANGO=2.0
install:
# command to install dependencies
  - "pip install coveralls"
  - "pip install pytz" # Needed for tests
  - pip install -q Django==$DJANGO
  - "pip install ."
# command to run tests
script:
  - coverage run --branch --source=notifications manage.py test
#matrix:
#  exclude:
#    - python: "X.X"
#      env: DJANGO=X.X


after_success:
  - coveralls
